sudo: required 
services: 
  - docker

before_install: 
  - docker build -t beersheep/fib-containers-client -f ./client/Dockerfile.dev ./client

# Test running session
script:
  - docker run -e CI=true beersheep/fib-containers-client npm test

after_success:
  - docker build -t beersheep/fib-containers-client ./client
  - docker build -t beersheep/fib-containers-server ./server
  - docker build -t beersheep/fib-containers-worker ./worker
  - docker build -t beersheep/fib-containers-nginx ./nginx
  # Login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push beersheep/fib-containers-client
  - docker push beersheep/fib-containers-server
  - docker push beersheep/fib-containers-worker
  - docker push beersheep/fib-containers-nginx
